stages:
  - deploy

variables:
  DEPLOY_PATH: /home/www/kitcrm

before_script:
  - echo "Start CI/CD"

deploy:
  stage: deploy
  tags:
    - kitcrm

  script:
    - |
      if [ -z "$DEPLOY_PATH" ]; then
        echo "ERROR: DEPLOY_PATH kosong!"
        exit 1
      fi

    - mkdir -p $DEPLOY_PATH
    - cd $DEPLOY_PATH

    - |
      if [ ! -d ".git" ]; then
        echo "Clone repository..."
        git clone https://gitlab.krakatau-it.co.id/ibnuqosim/crm .
      else
        echo "Pull latest code..."
        git pull origin main
      fi

    - echo "Start container..."
    - docker compose down
    - docker compose up -d --build --remove-orphans

    - echo "Wait container ready..."
    - sleep 5

    - docker compose ps

    - echo "Run Laravel optimization..."
    - docker compose exec -T app php artisan migrate --force
    - docker compose exec -T app php artisan config:cache
    - docker compose exec -T app php artisan route:cache
