stages:
  - build
  - deploy

variables:
  APP_DIR: /home/www/kitcrm

before_script:
  - echo "Start CI/CD"

build:
  stage: build
  script:
    - docker build -t kitcrm-app .

deploy:
  stage: deploy
  script:
    - echo "Deploy to server"
    - cd $DEPLOY_PATH
    - git pull origin main
    - docker compose down
    - docker compose up -d --build
