
services:

  app:
    build: .
    container_name: kitcrm_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: kitcrm_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web

  postgres:
    image: postgres:15
    container_name: kitcrm_postgres
    restart: always
    environment:
      POSTGRES_DB: kitcrm
      POSTGRES_USER: kitcrm
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:

volumes:
  pgdata:
